trigger: 
 branches:
   include:
     - main

pool: infrastructure

stages:
- stage: terraforminstallation
  jobs:
  - job: terraforminstallation
    displayName: terraform installation
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'monolithic'
        backendAzureRmOverrideSubscriptionID: 'b6571c78-f766-4999-8358-e9602abe50cf'
        backendAzureRmResourceGroupName: 'myResourceGroup'
        backendAzureRmStorageAccountName: 'avistorage888'
        backendAzureRmContainerName: 'avicnt'
        backendAzureRmKey: 'tf.statefile'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'monolithic'
        environmentAzureRmOverrideSubscriptionID: 'b6571c78-f766-4999-8358-e9602abe50cf'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'monolithic'
        environmentAzureRmOverrideSubscriptionID: 'b6571c78-f766-4999-8358-e9602abe50cf'